package patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.Project
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        add {
            feature {
                type = "CloudImage"
                id = "PROJECT_EXT_8"
                param("preemptible", "false")
                param("growingId", "false")
                param("zone", "us-west1-c")
                param("profileId", "google-3")
                param("agent_pool_id", "-2")
                param("sourceImage", "teamcity-2019-1")
                param("machineCustom", "false")
                param("maxInstances", "1")
                param("imageType", "Image")
                param("machineType", "f1-micro")
                param("source-id", "teamcity-2019-1")
                param("network", "teamcity-demo2-network")
            }
        }
        add {
            feature {
                type = "CloudProfile"
                id = "google-3"
                param("agentPushPreset", "")
                param("profileId", "google-3")
                param("profileServerUrl", "")
                param("name", "gcp")
                param("total-work-time", "")
                param("credentialsType", "environment")
                param("description", "")
                param("cloud-code", "google")
                param("terminate-idle-time", "30")
                param("enabled", "true")
                param("secure:accessKey", "")
            }
        }
    }
}
