package patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.Project
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with id = 'Build'
accordingly, and delete the patch script.
*/
changeProject(RelativeId("Build")) {
    features {
        add {
            feature {
                type = "CloudImage"
                id = "PROJECT_EXT_7"
                param("preemptible", "false")
                param("growingId", "false")
                param("zone", "asia-east1-a")
                param("profileId", "google-2")
                param("agent_pool_id", "-2")
                param("sourceImage", "teamcity-2019-1")
                param("machineCustom", "false")
                param("maxInstances", "1")
                param("imageType", "Image")
                param("machineType", "f1-micro")
                param("source-id", "teamcity-2019-1")
                param("network", "default")
            }
        }
        add {
            feature {
                type = "CloudProfile"
                id = "google-2"
                param("agentPushPreset", "")
                param("profileId", "google-2")
                param("profileServerUrl", "")
                param("name", "google")
                param("total-work-time", "")
                param("credentialsType", "environment")
                param("description", "")
                param("cloud-code", "google")
                param("terminate-idle-time", "30")
                param("enabled", "true")
                param("secure:accessKey", "")
            }
        }
    }
}
