package patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.Project
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with id = 'Deploy'
accordingly, and delete the patch script.
*/
changeProject(RelativeId("Deploy")) {
    features {
        add {
            feature {
                type = "project-graphs"
                id = "PROJECT_EXT_6"
                param("series", """
                    [
                      {
                        "type": "valueType",
                        "title": "Time Spent in Queue",
                        "sourceBuildTypeId": "Guestbook_DeployStaging",
                        "key": "TimeSpentInQueue"
                      }
                    ]
                """.trimIndent())
                param("format", "duration")
                param("hideFilters", "")
                param("title", "Time in the Build Queue")
                param("defaultFilters", "")
                param("seriesTitle", "Serie")
            }
        }
    }
}
