package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2018_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'HttpsGitCodecommitUsWest2amazonawsComV1reposGuestbook'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("HttpsGitCodecommitUsWest2amazonawsComV1reposGuestbook")
    name = "https://git-codecommit.us-west-2.amazonaws.com/v1/repos/guestbook"
    url = "https://git-codecommit.us-west-2.amazonaws.com/v1/repos/guestbook"
    authMethod = password {
        userName = "Yegor.Naumov-at-913206223978"
        password = "credentialsJSON:2821e831-6550-4a2c-aa10-8ba2842a8a7e"
    }
}))

