package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2018_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'HttpsGithubComDmitryTreskunovTeamcityGuestbookDemoRefsHeadsMaster'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("HttpsGithubComDmitryTreskunovTeamcityGuestbookDemoRefsHeadsMaster")
    name = "https://github.com/dmitry-treskunov/teamcity-guestbook-demo#refs/heads/master"
    url = "https://github.com/dmitry-treskunov/teamcity-guestbook-demo"
    authMethod = password {
        userName = "dmitry-treskunov"
        password = "credentialsJSON:5e59e9c7-a537-4328-851a-65391b10c060"
    }
}))

