package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2018_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'HttpsGithubComYegnauTeamcityGuestbookDemo'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("HttpsGithubComYegnauTeamcityGuestbookDemo")
    name = "https://github.com/yegnau/teamcity-guestbook-demo"
    url = "https://github.com/yegnau/teamcity-guestbook-demo"
}))

